version: "3.7" 
services:
  apache:
    image: 'php:8.0.6-apache'
    container_name: php
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'database'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
volumes:
  mysql: